import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-full min-h-full bg-slate-100">
        <main>
          <nav
            className="h-12 bg-pink-300 flex items-center
            justify-center gap-14 shadow-lg"
          >
            <Link href="/" className="font-medium">
              Home
            </Link>
            <Link href="/notes" className="font-medium">
              Notes
            </Link>
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
